2019-03-11 20:26:34,132 : kivy : Factory: 194 symbols loaded
2019-03-11 20:26:34,430 : kivy : Image: Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
2019-03-11 20:26:34,523 : kivy : VideoGstplayer: Using Gstreamer 1.10.2.0
2019-03-11 20:26:34,524 : kivy : Video: Provider: gstplayer
2019-03-11 20:26:34,616 : kivy : Loading MPF-MC controller
2019-03-11 20:26:34,617 : mpfmc : Mission Pinball Framework Media Controller v0.50.8
2019-03-11 20:26:34,617 : mpfmc : Mission Pinball Framework Game Engine v0.50.12
2019-03-11 20:26:34,618 : mpfmc : Machine path: C:\Users\Wilder\zelda\monitor
2019-03-11 20:26:34,619 : ConfigProcessor : Cache file not found: C:\Users\Wilder\AppData\Local\Temp\8f3d413d6cad112e06a9a4d036e68277.mpf_cache
2019-03-11 20:26:35,218 : ConfigProcessor : Loading config from file c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpfmc\mcconfig.yaml.
2019-03-11 20:26:35,297 : ConfigProcessor : Loading config: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpfmc\mcconfig.yaml
2019-03-11 20:26:35,298 : ConfigProcessor : Loading config from file C:\Users\Wilder\zelda\monitor\config\config.
2019-03-11 20:26:35,298 : kivy : Could not find file C:\Users\Wilder\zelda\monitor\config\config
Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 135, in load
    file = FileManager.locate_file(filename)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 108, in locate_file
    raise FileNotFoundError("File not found: {}".format(filename))
FileNotFoundError: File not found: C:\Users\Wilder\zelda\monitor\config\config

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpfmc\commands\mc.py", line 189, in __init__
    thread_stopper=thread_stopper).run()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mc.py", line 95, in __init__
    self.machine_config = self._load_config()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mc.py", line 224, in _load_config
    mpf_config = self.mpf_config_processor.load_config_files_with_cache(files, "machine", True)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 111, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 131, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 138, in load
    raise IOError("Could not find file {}".format(filename))
OSError: Could not find file C:\Users\Wilder\zelda\monitor\config\config
2019-03-11 20:26:35,300 : kivy : Stopping child threads... (0 remaining)
2019-03-11 20:26:35,300 : kivy : All child threads stopped.
