2019-05-20 23:24:50,253 : INFO : Machine : Mission Pinball Framework Core Engine v0.53.0-dev.16
2019-05-20 23:24:50,253 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'mpfconfigfile': 'c:\\users\\wilder\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2019-05-20-23-24-50-mpf-RedTunic.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 10, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2019-05-20 23:24:50,253 : INFO : Machine : MPF path: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf
2019-05-20 23:24:50,253 : INFO : Machine : Machine path: C:\Users\Wilder\zelda
2019-05-20 23:24:50,254 : INFO : Machine : Platform: win32
2019-05-20 23:24:50,254 : INFO : Machine : Python executable location: c:\users\wilder\appdata\local\programs\python\python36\python.exe
2019-05-20 23:24:50,254 : INFO : Machine : Python version: 3.6.4 (64-bit)
2019-05-20 23:24:50,254 : INFO : Machine : Machine config file #1: config.yaml
2019-05-20 23:24:50,256 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\Wilder\zelda\config\config.yaml
2019-05-20 23:24:50,257 : INFO : ConfigProcessor : Loading config from file c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\mpfconfig.yaml.
2019-05-20 23:24:50,257 : DEBUG : YAML File Interface : Loading file: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\mpfconfig.yaml
2019-05-20 23:24:50,464 : INFO : ConfigProcessor : Loading config: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\mpfconfig.yaml
2019-05-20 23:24:50,486 : INFO : ConfigProcessor : Loading config from file C:\Users\Wilder\zelda\config\config.yaml.
2019-05-20 23:24:50,486 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\config\config.yaml
2019-05-20 23:24:50,580 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\config\config.yaml
2019-05-20 23:24:50,580 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\config\hardware.yaml
2019-05-20 23:24:50,841 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\config\hardware.yaml
2019-05-20 23:24:50,844 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\config\keyboard.yaml
2019-05-20 23:24:50,868 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\config\keyboard.yaml
2019-05-20 23:24:50,871 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\config\videos.yaml
2019-05-20 23:24:50,970 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\config\videos.yaml
2019-05-20 23:24:50,981 : INFO : ConfigProcessor : Config file cache created: C:\Users\Wilder\AppData\Local\Temp\9bf880992bc5b85aa1bd2cc37b214e56.mpf_cache
2019-05-20 23:24:50,983 : DEBUG : asyncio : Using selector: SelectSelector
2019-05-20 23:24:50,984 : INFO : Machine : Initialise MPF.
2019-05-20 23:24:51,004 : DEBUG : Virtual Platform : Configuring virtual hardware interface.
2019-05-20 23:24:51,179 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2019-05-20 23:24:51,241 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\data/machine_vars.yaml
2019-05-20 23:24:51,244 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 226, 'prev_value': None, 'change': True}
2019-05-20 23:24:51,244 : INFO : EventManager : Event: ======'machine_var_player2_score'====== Args={'value': 94, 'prev_value': None, 'change': True}
2019-05-20 23:24:51,245 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.53.0-dev.16', 'prev_value': None, 'change': True}
2019-05-20 23:24:51,245 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.53.0-dev.16, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2019-05-20 23:24:51,245 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.6.4', 'prev_value': None, 'change': True}
2019-05-20 23:24:51,245 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-7-6.1.7601-SP1', 'prev_value': None, 'change': True}
2019-05-20 23:24:51,245 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2019-05-20 23:24:51,245 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '7', 'prev_value': None, 'change': True}
2019-05-20 23:24:51,245 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '6.1.7601', 'prev_value': None, 'change': True}
2019-05-20 23:24:51,246 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2019-05-20 23:24:51,246 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2019-05-20 23:24:51,298 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\96294a9578657f44941f2a8ec647ae36.mpf_cache
2019-05-20 23:24:51,302 : DEBUG : ModeController : Loaded mode rupee3x_finder
2019-05-20 23:24:51,302 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\Wilder\zelda\modes\light_world\config\light_world.yaml
2019-05-20 23:24:51,302 : INFO : ConfigProcessor : Loading config from file C:\Users\Wilder\zelda\modes\light_world\config\light_world.yaml.
2019-05-20 23:24:51,302 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\modes\light_world\config\light_world.yaml
2019-05-20 23:24:51,382 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\modes\light_world\config\light_world.yaml
2019-05-20 23:24:51,416 : INFO : ConfigProcessor : Config file cache created: C:\Users\Wilder\AppData\Local\Temp\072dbb4c30ca18f53440337aa5cd71bd.mpf_cache
2019-05-20 23:24:51,419 : DEBUG : ModeController : Loaded mode light_world
2019-05-20 23:24:51,419 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\7b0dcc699efc7732bf9d3e57ee202517.mpf_cache
2019-05-20 23:24:51,424 : DEBUG : ModeController : Loaded mode 2ballescape
2019-05-20 23:24:51,424 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\dd39e2de39eb354a1ec99be2f3167765.mpf_cache
2019-05-20 23:24:51,428 : DEBUG : ModeController : Loaded mode heartmeter
2019-05-20 23:24:51,428 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\Wilder\zelda\modes\base\config\base.yaml
2019-05-20 23:24:51,428 : INFO : ConfigProcessor : Loading config from file C:\Users\Wilder\zelda\modes\base\config\base.yaml.
2019-05-20 23:24:51,428 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\modes\base\config\base.yaml
2019-05-20 23:24:51,568 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\modes\base\config\base.yaml
2019-05-20 23:24:51,570 : INFO : ConfigProcessor : Config file cache created: C:\Users\Wilder\AppData\Local\Temp\4afc9f23ca6340163a8bb51d7deea78f.mpf_cache
2019-05-20 23:24:51,575 : DEBUG : ModeController : Loaded mode base
2019-05-20 23:24:51,575 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\58664c35241624b07b13025a5964d2a4.mpf_cache
2019-05-20 23:24:51,579 : DEBUG : ModeController : Loaded mode video_player
2019-05-20 23:24:51,579 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\fd6423453738b6cee138971698f65579.mpf_cache
2019-05-20 23:24:51,584 : DEBUG : ModeController : Loaded mode mode_tracker
2019-05-20 23:24:51,584 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\28e1731e516595966b3afcb08910cb63.mpf_cache
2019-05-20 23:24:51,589 : DEBUG : ModeController : Loaded mode heart_tracker
2019-05-20 23:24:51,589 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\3485f9bf4bb8d1d21be6de1438e091ba.mpf_cache
2019-05-20 23:24:51,594 : DEBUG : ModeController : Loaded mode skillshot_ballsave
2019-05-20 23:24:51,594 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\43a06f52d0e9cf0597140b4c27159d40.mpf_cache
2019-05-20 23:24:51,599 : DEBUG : ModeController : Loaded mode escapehurryup
2019-05-20 23:24:51,599 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\6caaa2c03f737135abd403644138525e.mpf_cache
2019-05-20 23:24:51,603 : DEBUG : ModeController : Loaded mode shop
2019-05-20 23:24:51,603 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\Wilder\zelda\modes\item_tracker\config\item_tracker.yaml
2019-05-20 23:24:51,603 : INFO : ConfigProcessor : Loading config from file C:\Users\Wilder\zelda\modes\item_tracker\config\item_tracker.yaml.
2019-05-20 23:24:51,604 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\modes\item_tracker\config\item_tracker.yaml
2019-05-20 23:24:51,701 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\modes\item_tracker\config\item_tracker.yaml
2019-05-20 23:24:51,704 : INFO : ConfigProcessor : Config file cache created: C:\Users\Wilder\AppData\Local\Temp\c3fd2c292a6c0d3463ad9b4555730ad5.mpf_cache
2019-05-20 23:24:51,711 : DEBUG : ModeController : Loaded mode item_tracker
2019-05-20 23:24:51,712 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\Wilder\zelda\modes\slide_tracker\config\slide_tracker.yaml
2019-05-20 23:24:51,712 : INFO : ConfigProcessor : Loading config from file C:\Users\Wilder\zelda\modes\slide_tracker\config\slide_tracker.yaml.
2019-05-20 23:24:51,712 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\modes\slide_tracker\config\slide_tracker.yaml
2019-05-20 23:24:51,794 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\modes\slide_tracker\config\slide_tracker.yaml
2019-05-20 23:24:51,795 : INFO : ConfigProcessor : Config file cache created: C:\Users\Wilder\AppData\Local\Temp\dbd150f896646081271b7a77a791f2fa.mpf_cache
2019-05-20 23:24:51,799 : DEBUG : ModeController : Loaded mode slide_tracker
2019-05-20 23:24:51,800 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\Wilder\zelda\modes\2ballqualifier\config\2ballqualifier.yaml
2019-05-20 23:24:51,800 : INFO : ConfigProcessor : Loading config from file C:\Users\Wilder\zelda\modes\2ballqualifier\config\2ballqualifier.yaml.
2019-05-20 23:24:51,801 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\modes\2ballqualifier\config\2ballqualifier.yaml
2019-05-20 23:24:51,866 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...column 3\'',)>) at c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py:96
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...column 3\'',)>) at c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py:96>
Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 198, in load
    config = self.process(f)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 224, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 104, in get_single_data
    return self.construct_document(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 114, in construct_document
    for dummy in generator:
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 611, in construct_yaml_map
    value = self.construct_mapping(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 135, in construct_mapping
    format(key, key_node.start_mark))
KeyError: 'Key "start_2ball_multiball" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\2ballqualifier\\config\\2ballqualifier.yaml", line 133, column 3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 99, in _async_handler_done
    future.result()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 117, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 266, in _load_mode
    config = self._load_mode_config(mode_string)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 184, in _load_mode_config
    store_to_cache=self.machine.options['create_config_cache'])
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 132, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 99, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 212, in load
    raise ValueError(msg)
ValueError: Error found in file C:\Users\Wilder\zelda\modes\2ballqualifier\config\2ballqualifier.yaml: 'Key "start_2ball_multiball" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\2ballqualifier\\config\\2ballqualifier.yaml", line 133, column 3'
2019-05-20 23:24:51,964 : INFO : Machine : Starting the main run loop.
2019-05-20 23:24:51,965 : INFO : Machine : Shutting down...
2019-05-20 23:24:51,965 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2019-05-20 23:24:52,131 : ERROR : root : Error found in file C:\Users\Wilder\zelda\modes\2ballqualifier\config\2ballqualifier.yaml: 'Key "start_2ball_multiball" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\2ballqualifier\\config\\2ballqualifier.yaml", line 133, column 3'
Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 198, in load
    config = self.process(f)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 224, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 104, in get_single_data
    return self.construct_document(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 114, in construct_document
    for dummy in generator:
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 611, in construct_yaml_map
    value = self.construct_mapping(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 135, in construct_mapping
    format(key, key_node.start_mark))
KeyError: 'Key "start_2ball_multiball" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\2ballqualifier\\config\\2ballqualifier.yaml", line 133, column 3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\commands\game.py", line 220, in __init__
    MachineController(mpf_path, machine_path, vars(self.args)).run()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 716, in run
    self._run_loop()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 776, in _run_loop
    raise self._exception['exception']
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 99, in _async_handler_done
    future.result()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 117, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 266, in _load_mode
    config = self._load_mode_config(mode_string)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 184, in _load_mode_config
    store_to_cache=self.machine.options['create_config_cache'])
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 132, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 99, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 212, in load
    raise ValueError(msg)
ValueError: Error found in file C:\Users\Wilder\zelda\modes\2ballqualifier\config\2ballqualifier.yaml: 'Key "start_2ball_multiball" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\2ballqualifier\\config\\2ballqualifier.yaml", line 133, column 3'
