2019-04-30 13:35:08,114 : kivy : Factory: 194 symbols loaded
2019-04-30 13:35:08,118 : kivy : Cache: register <kv.lang> with limit=None, timeout=None
2019-04-30 13:35:08,271 : kivy : Cache: register <kv.image> with limit=None, timeout=60
2019-04-30 13:35:08,271 : kivy : Cache: register <kv.atlas> with limit=None, timeout=None
2019-04-30 13:35:08,292 : kivy : Image: Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
2019-04-30 13:35:08,292 : kivy : Cache: register <kv.texture> with limit=1000, timeout=60
2019-04-30 13:35:08,292 : kivy : Cache: register <kv.shader> with limit=1000, timeout=3600
2019-04-30 13:35:08,364 : kivy : VideoGstplayer: Using Gstreamer 1.10.2.0
2019-04-30 13:35:08,364 : kivy : Video: Provider: gstplayer
2019-04-30 13:35:08,448 : kivy : Loading MPF-MC controller
2019-04-30 13:35:08,449 : mpfmc : Mission Pinball Framework Media Controller v0.53.0-dev.0
2019-04-30 13:35:08,449 : mpfmc : Mission Pinball Framework Game Engine v0.53.0-dev.16
2019-04-30 13:35:08,449 : mpfmc : Machine path: C:\Users\Wilder\zelda
2019-04-30 13:35:08,451 : ConfigProcessor : Cache file not found: C:\Users\Wilder\AppData\Local\Temp\3e6d4d663fa9c5c5893f6121084dd4db.mpf_cache
2019-04-30 13:35:08,451 : ConfigProcessor : Loading config from file c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpfmc\mcconfig.yaml.
2019-04-30 13:35:08,451 : YAML File Interface : Loading file: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpfmc\mcconfig.yaml
2019-04-30 13:35:08,559 : ConfigProcessor : Loading config: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpfmc\mcconfig.yaml
2019-04-30 13:35:08,573 : ConfigProcessor : Loading config from file C:\Users\Wilder\zelda\config\x.
2019-04-30 13:35:08,574 : kivy : Could not find file C:\Users\Wilder\zelda\config\x
Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 80, in load
    file = FileManager.locate_file(filename)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 53, in locate_file
    raise FileNotFoundError("File not found: {}".format(filename))
FileNotFoundError: File not found: C:\Users\Wilder\zelda\config\x

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpfmc\commands\mc.py", line 209, in __init__
    thread_stopper=thread_stopper).run()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mc.py", line 97, in __init__
    self.machine_config = self._load_config()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mc.py", line 223, in _load_config
    mpf_config = self.mpf_config_processor.load_config_files_with_cache(files, "machine", True)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 132, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 83, in load
    raise IOError("Could not find file {}".format(filename))
OSError: Could not find file C:\Users\Wilder\zelda\config\x
2019-04-30 13:35:08,575 : kivy : Stopping child threads... (0 remaining)
2019-04-30 13:35:08,576 : kivy : All child threads stopped.
