2019-05-01 18:03:33,330 : INFO : Machine : Mission Pinball Framework Core Engine v0.53.0-dev.16
2019-05-01 18:03:33,330 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'mpfconfigfile': 'c:\\users\\wilder\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2019-05-01-18-03-33-mpf-RedTunic.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 10, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2019-05-01 18:03:33,330 : INFO : Machine : MPF path: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf
2019-05-01 18:03:33,330 : INFO : Machine : Machine path: C:\Users\Wilder\zelda
2019-05-01 18:03:33,331 : INFO : Machine : Platform: win32
2019-05-01 18:03:33,331 : INFO : Machine : Python executable location: c:\users\wilder\appdata\local\programs\python\python36\python.exe
2019-05-01 18:03:33,331 : INFO : Machine : Python version: 3.6.4 (64-bit)
2019-05-01 18:03:33,331 : INFO : Machine : Machine config file #1: config.yaml
2019-05-01 18:03:33,358 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\9bf880992bc5b85aa1bd2cc37b214e56.mpf_cache
2019-05-01 18:03:33,360 : DEBUG : asyncio : Using selector: SelectSelector
2019-05-01 18:03:33,361 : INFO : Machine : Initialise MPF.
2019-05-01 18:03:33,406 : DEBUG : FAST : Configuring FAST hardware.
2019-05-01 18:03:33,599 : INFO : FAST : Connecting to \\.\COM11 at 921600bps
2019-05-01 18:03:33,632 : INFO : FAST : Connected! Processor: NET, Board Type: FP-CPU-002-2, Firmware: 01.02
2019-05-01 18:03:33,633 : INFO : EventManager : Event: ======'machine_var_fast_net_firmware'====== Args={'value': '01.02', 'prev_value': None, 'change': True}
2019-05-01 18:03:33,633 : INFO : EventManager : Event: ======'machine_var_fast_net_model'====== Args={'value': 'FP-CPU-002-2', 'prev_value': None, 'change': True}
2019-05-01 18:03:33,633 : WARNING : FAST : Not resetting FAST NET because firmware is currently broken.
2019-05-01 18:03:33,696 : INFO : FAST : Connecting to \\.\COM12 at 921600bps
2019-05-01 18:03:33,744 : INFO : FAST : Connected! Processor: RGB, Board Type: FP-CPU-002-2, Firmware: 01.00
2019-05-01 18:03:33,745 : INFO : EventManager : Event: ======'machine_var_fast_rgb_firmware'====== Args={'value': '01.00', 'prev_value': None, 'change': True}
2019-05-01 18:03:33,745 : INFO : EventManager : Event: ======'machine_var_fast_rgb_model'====== Args={'value': 'FP-CPU-002-2', 'prev_value': None, 'change': True}
2019-05-01 18:03:33,745 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2019-05-01 18:03:33,812 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\data/machine_vars.yaml
2019-05-01 18:03:33,815 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 481, 'prev_value': None, 'change': True}
2019-05-01 18:03:33,815 : INFO : EventManager : Event: ======'machine_var_player2_score'====== Args={'value': 0, 'prev_value': None, 'change': True}
2019-05-01 18:03:33,816 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.53.0-dev.16', 'prev_value': None, 'change': True}
2019-05-01 18:03:33,816 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.53.0-dev.16, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2019-05-01 18:03:33,816 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.6.4', 'prev_value': None, 'change': True}
2019-05-01 18:03:33,816 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-7-6.1.7601-SP1', 'prev_value': None, 'change': True}
2019-05-01 18:03:33,816 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2019-05-01 18:03:33,816 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '7', 'prev_value': None, 'change': True}
2019-05-01 18:03:33,816 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '6.1.7601', 'prev_value': None, 'change': True}
2019-05-01 18:03:33,817 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2019-05-01 18:03:33,817 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2019-05-01 18:03:33,883 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\f394a72c4810bb1cc42cac0690a90dcf.mpf_cache
2019-05-01 18:03:33,886 : DEBUG : ModeController : Loaded mode gameoverplayer
2019-05-01 18:03:33,887 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\696ab9654b1d369e3597af15c079ad3b.mpf_cache
2019-05-01 18:03:33,890 : DEBUG : ModeController : Loaded mode ganon_battle
2019-05-01 18:03:33,891 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\b0bcc174d8c9595c3b107b2ba9cf1c73.mpf_cache
2019-05-01 18:03:33,897 : DEBUG : ModeController : Loaded mode attract_carousel
2019-05-01 18:03:33,898 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\27a949ddf2d3e5eeb9247bd991aba200.mpf_cache
2019-05-01 18:03:33,902 : DEBUG : ModeController : Loaded mode darkworld2
2019-05-01 18:03:33,902 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\fd6423453738b6cee138971698f65579.mpf_cache
2019-05-01 18:03:33,907 : DEBUG : ModeController : Loaded mode mode_tracker
2019-05-01 18:03:33,907 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\8b601767b8d464abeaa513b42e6346a8.mpf_cache
2019-05-01 18:03:33,911 : DEBUG : ModeController : Loaded mode master_sword_buildup
2019-05-01 18:03:33,911 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\6fd2b5e36bbbd9c12f9ee3aa32f1ceca.mpf_cache
2019-05-01 18:03:33,915 : DEBUG : ModeController : Loaded mode ball_hold_tracker
2019-05-01 18:03:33,915 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\c3fd2c292a6c0d3463ad9b4555730ad5.mpf_cache
2019-05-01 18:03:33,920 : DEBUG : ModeController : Loaded mode item_tracker
2019-05-01 18:03:33,920 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\225554da95d8871f7382aa94a6d6b3eb.mpf_cache
2019-05-01 18:03:33,925 : DEBUG : ModeController : Loaded mode lost_woods_starter
2019-05-01 18:03:33,925 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\c5e5b78d841dff96974ddb92030af0a9.mpf_cache
2019-05-01 18:03:33,929 : DEBUG : ModeController : Loaded mode skill_shot
2019-05-01 18:03:33,929 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\96294a9578657f44941f2a8ec647ae36.mpf_cache
2019-05-01 18:03:33,933 : DEBUG : ModeController : Loaded mode rupee3x_finder
2019-05-01 18:03:33,933 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\3485f9bf4bb8d1d21be6de1438e091ba.mpf_cache
2019-05-01 18:03:33,937 : DEBUG : ModeController : Loaded mode skillshot_ballsave
2019-05-01 18:03:33,937 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\c35ad2e595070cac0b6f696d6f7f6af6.mpf_cache
2019-05-01 18:03:33,941 : DEBUG : ModeController : Loaded mode ball_save
2019-05-01 18:03:33,941 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\7b0dcc699efc7732bf9d3e57ee202517.mpf_cache
2019-05-01 18:03:33,945 : DEBUG : ModeController : Loaded mode 2ballescape
2019-05-01 18:03:33,945 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\05768db999abb9e30be16a432a0581c8.mpf_cache
2019-05-01 18:03:33,949 : DEBUG : ModeController : Loaded mode extraball
2019-05-01 18:03:33,949 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\43a06f52d0e9cf0597140b4c27159d40.mpf_cache
2019-05-01 18:03:33,953 : DEBUG : ModeController : Loaded mode escapehurryup
2019-05-01 18:03:33,953 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\fc30620fce8f82c18fed051cdde27ef9.mpf_cache
2019-05-01 18:03:33,957 : DEBUG : ModeController : Loaded mode 5waycombotracker
2019-05-01 18:03:33,957 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\d9d23a2a9a3117f1553491692ff1c689.mpf_cache
2019-05-01 18:03:33,961 : DEBUG : ModeController : Loaded mode playfield_multiplier
2019-05-01 18:03:33,961 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\072dbb4c30ca18f53440337aa5cd71bd.mpf_cache
2019-05-01 18:03:33,965 : DEBUG : ModeController : Loaded mode light_world
2019-05-01 18:03:33,965 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\58664c35241624b07b13025a5964d2a4.mpf_cache
2019-05-01 18:03:33,969 : DEBUG : ModeController : Loaded mode video_player
2019-05-01 18:03:33,969 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\562f2c62ffb495bc414930beede29530.mpf_cache
2019-05-01 18:03:33,976 : DEBUG : ModeController : Loaded mode game_ender_mode
2019-05-01 18:03:33,976 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\58a9cd5447353eacedab412f1c10b0ab.mpf_cache
2019-05-01 18:03:33,980 : DEBUG : ModeController : Loaded mode lost_woods
2019-05-01 18:03:33,980 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\da675f6b180b79eecb40cb5eb7f75a18.mpf_cache
2019-05-01 18:03:33,986 : DEBUG : ModeController : Loaded mode bomb_finder
2019-05-01 18:03:33,986 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\34c6448537d1c95c89cf73a07c0f99c9.mpf_cache
2019-05-01 18:03:33,990 : DEBUG : ModeController : Loaded mode bottle_filler
2019-05-01 18:03:33,990 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\6cbeeb809d9de6fbbf2951c4e6867473.mpf_cache
2019-05-01 18:03:33,994 : DEBUG : ModeController : Loaded mode darkworld
2019-05-01 18:03:33,994 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\4afc9f23ca6340163a8bb51d7deea78f.mpf_cache
2019-05-01 18:03:33,998 : DEBUG : ModeController : Loaded mode base
2019-05-01 18:03:33,998 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\916c9e2d9177837f45e9cdbb7c1d0b93.mpf_cache
2019-05-01 18:03:34,003 : DEBUG : ModeController : Loaded mode unusual_show_tracker
2019-05-01 18:03:34,003 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\Wilder\zelda\modes\final_hold\config\final_hold.yaml
2019-05-01 18:03:34,003 : INFO : ConfigProcessor : Loading config from file C:\Users\Wilder\zelda\modes\final_hold\config\final_hold.yaml.
2019-05-01 18:03:34,004 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\modes\final_hold\config\final_hold.yaml
2019-05-01 18:03:34,025 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...column 7\'',)>) at c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py:96
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...column 7\'',)>) at c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py:96>
Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 198, in load
    config = self.process(f)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 224, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 104, in get_single_data
    return self.construct_document(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 114, in construct_document
    for dummy in generator:
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 611, in construct_yaml_map
    value = self.construct_mapping(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 135, in construct_mapping
    format(key, key_node.start_mark))
KeyError: 'Key "speed" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\final_hold\\config\\final_hold.yaml", line 51, column 7'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 99, in _async_handler_done
    future.result()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 117, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 266, in _load_mode
    config = self._load_mode_config(mode_string)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 184, in _load_mode_config
    store_to_cache=self.machine.options['create_config_cache'])
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 132, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 99, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 212, in load
    raise ValueError(msg)
ValueError: Error found in file C:\Users\Wilder\zelda\modes\final_hold\config\final_hold.yaml: 'Key "speed" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\final_hold\\config\\final_hold.yaml", line 51, column 7'
2019-05-01 18:03:34,030 : INFO : Machine : Starting the main run loop.
2019-05-01 18:03:34,030 : INFO : Machine : Shutting down...
2019-05-01 18:03:34,030 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2019-05-01 18:03:34,033 : ERROR : FAST : Stop called on serial connection \\.\COM12
2019-05-01 18:03:34,034 : ERROR : FAST : Stop called on serial connection \\.\COM11
2019-05-01 18:03:34,342 : ERROR : root : Error found in file C:\Users\Wilder\zelda\modes\final_hold\config\final_hold.yaml: 'Key "speed" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\final_hold\\config\\final_hold.yaml", line 51, column 7'
Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 198, in load
    config = self.process(f)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 224, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 104, in get_single_data
    return self.construct_document(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 114, in construct_document
    for dummy in generator:
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 611, in construct_yaml_map
    value = self.construct_mapping(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 135, in construct_mapping
    format(key, key_node.start_mark))
KeyError: 'Key "speed" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\final_hold\\config\\final_hold.yaml", line 51, column 7'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\commands\game.py", line 220, in __init__
    MachineController(mpf_path, machine_path, vars(self.args)).run()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 716, in run
    self._run_loop()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 776, in _run_loop
    raise self._exception['exception']
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 99, in _async_handler_done
    future.result()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 117, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 266, in _load_mode
    config = self._load_mode_config(mode_string)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 184, in _load_mode_config
    store_to_cache=self.machine.options['create_config_cache'])
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 132, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 99, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 212, in load
    raise ValueError(msg)
ValueError: Error found in file C:\Users\Wilder\zelda\modes\final_hold\config\final_hold.yaml: 'Key "speed" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\final_hold\\config\\final_hold.yaml", line 51, column 7'
