2019-04-03 13:13:36,306 : INFO : Machine : Mission Pinball Framework Core Engine v0.52.1
2019-04-03 13:13:36,307 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'mpfconfigfile': 'c:\\users\\wilder\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2019-04-03-13-13-36-mpf-RedTunic.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 10, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2019-04-03 13:13:36,307 : INFO : Machine : MPF path: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf
2019-04-03 13:13:36,307 : INFO : Machine : Machine path: C:\Users\Wilder\zelda
2019-04-03 13:13:36,307 : INFO : Machine : Platform: win32
2019-04-03 13:13:36,307 : INFO : Machine : Python executable location: c:\users\wilder\appdata\local\programs\python\python36\python.exe
2019-04-03 13:13:36,308 : INFO : Machine : Python version: 3.6.4 (64-bit)
2019-04-03 13:13:36,308 : INFO : Machine : Machine config file #1: config.yaml
2019-04-03 13:13:36,310 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\Wilder\zelda\config\config.yaml
2019-04-03 13:13:36,310 : INFO : ConfigProcessor : Loading config from file c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\mpfconfig.yaml.
2019-04-03 13:13:36,310 : DEBUG : YAML File Interface : Loading file: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\mpfconfig.yaml
2019-04-03 13:13:36,518 : INFO : ConfigProcessor : Loading config: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\mpfconfig.yaml
2019-04-03 13:13:36,539 : INFO : ConfigProcessor : Loading config from file C:\Users\Wilder\zelda\config\config.yaml.
2019-04-03 13:13:36,539 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\config\config.yaml
2019-04-03 13:13:36,619 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\config\config.yaml
2019-04-03 13:13:36,619 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\config\hardware.yaml
2019-04-03 13:13:36,930 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\config\hardware.yaml
2019-04-03 13:13:36,933 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\config\keyboard.yaml
2019-04-03 13:13:36,963 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\config\keyboard.yaml
2019-04-03 13:13:36,966 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\config\videos.yaml
2019-04-03 13:13:37,080 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\config\videos.yaml
2019-04-03 13:13:37,089 : INFO : ConfigProcessor : Config file cache created: C:\Users\Wilder\AppData\Local\Temp\9bf880992bc5b85aa1bd2cc37b214e56.mpf_cache
2019-04-03 13:13:37,092 : DEBUG : asyncio : Using selector: SelectSelector
2019-04-03 13:13:37,093 : INFO : Machine : Initialise MPF.
2019-04-03 13:13:37,135 : DEBUG : Virtual Platform : Configuring virtual hardware interface.
2019-04-03 13:13:37,346 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2019-04-03 13:13:37,418 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\data/machine_vars.yaml
2019-04-03 13:13:37,421 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 5, 'prev_value': None, 'change': True}
2019-04-03 13:13:37,421 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.52.1', 'prev_value': None, 'change': True}
2019-04-03 13:13:37,421 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.52.1, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2019-04-03 13:13:37,421 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.6.4', 'prev_value': None, 'change': True}
2019-04-03 13:13:37,422 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-7-6.1.7601-SP1', 'prev_value': None, 'change': True}
2019-04-03 13:13:37,422 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2019-04-03 13:13:37,422 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '7', 'prev_value': None, 'change': True}
2019-04-03 13:13:37,422 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '6.1.7601', 'prev_value': None, 'change': True}
2019-04-03 13:13:37,422 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2019-04-03 13:13:37,422 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2019-04-03 13:13:37,486 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\7b0dcc699efc7732bf9d3e57ee202517.mpf_cache
2019-04-03 13:13:37,492 : DEBUG : ModeController : Loaded mode 2ballescape
2019-04-03 13:13:37,492 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\Wilder\zelda\modes\agahnim_multiball\config\agahnim_multiball.yaml
2019-04-03 13:13:37,492 : INFO : ConfigProcessor : Loading config from file C:\Users\Wilder\zelda\modes\agahnim_multiball\config\agahnim_multiball.yaml.
2019-04-03 13:13:37,493 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\modes\agahnim_multiball\config\agahnim_multiball.yaml
2019-04-03 13:13:37,547 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\modes\agahnim_multiball\config\agahnim_multiball.yaml
2019-04-03 13:13:37,548 : INFO : ConfigProcessor : Config file cache created: C:\Users\Wilder\AppData\Local\Temp\a31feedcb4b85bf76d76fe6a1222bc90.mpf_cache
2019-04-03 13:13:37,551 : DEBUG : ModeController : Loaded mode agahnim_multiball
2019-04-03 13:13:37,551 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\b0ee6a771658ae3fb7e70c6d5ff59887.mpf_cache
2019-04-03 13:13:37,563 : DEBUG : ModeController : Loaded mode game
2019-04-03 13:13:37,563 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\43a06f52d0e9cf0597140b4c27159d40.mpf_cache
2019-04-03 13:13:37,568 : DEBUG : ModeController : Loaded mode escapehurryup
2019-04-03 13:13:37,568 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\8b601767b8d464abeaa513b42e6346a8.mpf_cache
2019-04-03 13:13:37,573 : DEBUG : ModeController : Loaded mode master_sword_buildup
2019-04-03 13:13:37,573 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\cb8b20150020107be74f23a2ee427f56.mpf_cache
2019-04-03 13:13:37,580 : DEBUG : ModeController : Loaded mode high_score
2019-04-03 13:13:37,580 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\05768db999abb9e30be16a432a0581c8.mpf_cache
2019-04-03 13:13:37,585 : DEBUG : ModeController : Loaded mode extraball
2019-04-03 13:13:37,585 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\1f8ff34a8859f8c62d77912f33e29b9c.mpf_cache
2019-04-03 13:13:37,590 : DEBUG : ModeController : Loaded mode 2ballqualifier
2019-04-03 13:13:37,590 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\Wilder\zelda\modes\playfield_multiplier\config\playfield_multiplier.yaml
2019-04-03 13:13:37,590 : INFO : ConfigProcessor : Loading config from file C:\Users\Wilder\zelda\modes\playfield_multiplier\config\playfield_multiplier.yaml.
2019-04-03 13:13:37,591 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\modes\playfield_multiplier\config\playfield_multiplier.yaml
2019-04-03 13:13:37,615 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\modes\playfield_multiplier\config\playfield_multiplier.yaml
2019-04-03 13:13:37,616 : INFO : ConfigProcessor : Config file cache created: C:\Users\Wilder\AppData\Local\Temp\d9d23a2a9a3117f1553491692ff1c689.mpf_cache
2019-04-03 13:13:37,619 : DEBUG : ModeController : Loaded mode playfield_multiplier
2019-04-03 13:13:37,619 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\Wilder\zelda\modes\light_world\config\light_world.yaml
2019-04-03 13:13:37,619 : INFO : ConfigProcessor : Loading config from file C:\Users\Wilder\zelda\modes\light_world\config\light_world.yaml.
2019-04-03 13:13:37,620 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\modes\light_world\config\light_world.yaml
2019-04-03 13:13:37,701 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...column 3\'',)>) at c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py:96
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...column 3\'',)>) at c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py:96>
Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 198, in load
    config = self.process(f)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 224, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 104, in get_single_data
    return self.construct_document(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 114, in construct_document
    for dummy in generator:
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 611, in construct_yaml_map
    value = self.construct_mapping(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 135, in construct_mapping
    format(key, key_node.start_mark))
KeyError: 'Key "s_droptarget2_hit" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\light_world\\config\\light_world.yaml", line 211, column 3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 99, in _async_handler_done
    future.result()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 117, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 266, in _load_mode
    config = self._load_mode_config(mode_string)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 184, in _load_mode_config
    store_to_cache=self.machine.options['create_config_cache'])
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 132, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 99, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 212, in load
    raise ValueError(msg)
ValueError: Error found in file C:\Users\Wilder\zelda\modes\light_world\config\light_world.yaml: 'Key "s_droptarget2_hit" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\light_world\\config\\light_world.yaml", line 211, column 3'
2019-04-03 13:13:37,705 : INFO : Machine : Starting the main run loop.
2019-04-03 13:13:37,706 : INFO : Machine : Shutting down...
2019-04-03 13:13:37,706 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2019-04-03 13:13:37,814 : ERROR : root : Error found in file C:\Users\Wilder\zelda\modes\light_world\config\light_world.yaml: 'Key "s_droptarget2_hit" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\light_world\\config\\light_world.yaml", line 211, column 3'
Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 198, in load
    config = self.process(f)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 224, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 104, in get_single_data
    return self.construct_document(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 114, in construct_document
    for dummy in generator:
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 611, in construct_yaml_map
    value = self.construct_mapping(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 135, in construct_mapping
    format(key, key_node.start_mark))
KeyError: 'Key "s_droptarget2_hit" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\light_world\\config\\light_world.yaml", line 211, column 3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\commands\game.py", line 220, in __init__
    MachineController(mpf_path, machine_path, vars(self.args)).run()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 709, in run
    self._run_loop()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 769, in _run_loop
    raise self._exception['exception']
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 99, in _async_handler_done
    future.result()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 117, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 266, in _load_mode
    config = self._load_mode_config(mode_string)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 184, in _load_mode_config
    store_to_cache=self.machine.options['create_config_cache'])
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 132, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 99, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 212, in load
    raise ValueError(msg)
ValueError: Error found in file C:\Users\Wilder\zelda\modes\light_world\config\light_world.yaml: 'Key "s_droptarget2_hit" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\light_world\\config\\light_world.yaml", line 211, column 3'
