2019-05-28 21:22:20,963 : INFO : Machine : Mission Pinball Framework Core Engine v0.53.0-dev.16
2019-05-28 21:22:20,964 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'mpfconfigfile': 'c:\\users\\wilder\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2019-05-28-21-22-20-mpf-RedTunic.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 10, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2019-05-28 21:22:20,964 : INFO : Machine : MPF path: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf
2019-05-28 21:22:20,964 : INFO : Machine : Machine path: C:\Users\Wilder\zelda
2019-05-28 21:22:20,964 : INFO : Machine : Platform: win32
2019-05-28 21:22:20,964 : INFO : Machine : Python executable location: c:\users\wilder\appdata\local\programs\python\python36\python.exe
2019-05-28 21:22:20,964 : INFO : Machine : Python version: 3.6.4 (64-bit)
2019-05-28 21:22:20,964 : INFO : Machine : Machine config file #1: config.yaml
2019-05-28 21:22:20,966 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\9bf880992bc5b85aa1bd2cc37b214e56.mpf_cache
2019-05-28 21:22:20,968 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\Wilder\zelda\config\hardware.yaml
2019-05-28 21:22:20,968 : INFO : ConfigProcessor : Loading config from file c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\mpfconfig.yaml.
2019-05-28 21:22:20,969 : DEBUG : YAML File Interface : Loading file: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\mpfconfig.yaml
2019-05-28 21:22:21,196 : INFO : ConfigProcessor : Loading config: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\mpfconfig.yaml
2019-05-28 21:22:21,214 : INFO : ConfigProcessor : Loading config from file C:\Users\Wilder\zelda\config\config.yaml.
2019-05-28 21:22:21,215 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\config\config.yaml
2019-05-28 21:22:21,344 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\config\config.yaml
2019-05-28 21:22:21,344 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\config\hardware.yaml
2019-05-28 21:22:21,699 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\config\hardware.yaml
2019-05-28 21:22:21,728 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\config\keyboard.yaml
2019-05-28 21:22:21,763 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\config\keyboard.yaml
2019-05-28 21:22:21,822 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\config\videos.yaml
2019-05-28 21:22:22,072 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\config\videos.yaml
2019-05-28 21:22:22,086 : INFO : ConfigProcessor : Config file cache created: C:\Users\Wilder\AppData\Local\Temp\9bf880992bc5b85aa1bd2cc37b214e56.mpf_cache
2019-05-28 21:22:22,088 : DEBUG : asyncio : Using selector: SelectSelector
2019-05-28 21:22:22,090 : INFO : Machine : Initialise MPF.
2019-05-28 21:22:22,392 : DEBUG : FAST : Configuring FAST hardware.
2019-05-28 21:22:23,300 : INFO : FAST : Connecting to \\.\COM11 at 921600bps
2019-05-28 21:22:23,368 : INFO : FAST : Connected! Processor: NET, Board Type: FP-CPU-002-2, Firmware: 01.02
2019-05-28 21:22:23,368 : INFO : EventManager : Event: ======'machine_var_fast_net_firmware'====== Args={'value': '01.02', 'prev_value': None, 'change': True}
2019-05-28 21:22:23,368 : INFO : EventManager : Event: ======'machine_var_fast_net_model'====== Args={'value': 'FP-CPU-002-2', 'prev_value': None, 'change': True}
2019-05-28 21:22:23,368 : WARNING : FAST : Not resetting FAST NET because firmware is currently broken.
2019-05-28 21:22:23,432 : INFO : FAST : Connecting to \\.\COM12 at 921600bps
2019-05-28 21:22:23,464 : INFO : FAST : Connected! Processor: RGB, Board Type: FP-CPU-002-2, Firmware: 01.00
2019-05-28 21:22:23,464 : INFO : EventManager : Event: ======'machine_var_fast_rgb_firmware'====== Args={'value': '01.00', 'prev_value': None, 'change': True}
2019-05-28 21:22:23,464 : INFO : EventManager : Event: ======'machine_var_fast_rgb_model'====== Args={'value': 'FP-CPU-002-2', 'prev_value': None, 'change': True}
2019-05-28 21:22:23,465 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2019-05-28 21:22:24,716 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\data/machine_vars.yaml
2019-05-28 21:22:24,723 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 1353, 'prev_value': None, 'change': True}
2019-05-28 21:22:24,723 : INFO : EventManager : Event: ======'machine_var_player2_score'====== Args={'value': 0, 'prev_value': None, 'change': True}
2019-05-28 21:22:24,724 : INFO : EventManager : Event: ======'machine_var_player3_score'====== Args={'value': 0, 'prev_value': None, 'change': True}
2019-05-28 21:22:24,724 : INFO : EventManager : Event: ======'machine_var_player4_score'====== Args={'value': 0, 'prev_value': None, 'change': True}
2019-05-28 21:22:24,724 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.53.0-dev.16', 'prev_value': None, 'change': True}
2019-05-28 21:22:24,724 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.53.0-dev.16, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2019-05-28 21:22:24,724 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.6.4', 'prev_value': None, 'change': True}
2019-05-28 21:22:24,725 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-7-6.1.7601-SP1', 'prev_value': None, 'change': True}
2019-05-28 21:22:24,725 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2019-05-28 21:22:24,725 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '7', 'prev_value': None, 'change': True}
2019-05-28 21:22:24,725 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '6.1.7601', 'prev_value': None, 'change': True}
2019-05-28 21:22:24,725 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2019-05-28 21:22:24,725 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2019-05-28 21:22:30,141 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\cb8b20150020107be74f23a2ee427f56.mpf_cache
2019-05-28 21:22:30,982 : DEBUG : ModeController : Loaded mode high_score
2019-05-28 21:22:31,020 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\072dbb4c30ca18f53440337aa5cd71bd.mpf_cache
2019-05-28 21:22:31,059 : DEBUG : ModeController : Loaded mode light_world
2019-05-28 21:22:31,061 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\6fd2b5e36bbbd9c12f9ee3aa32f1ceca.mpf_cache
2019-05-28 21:22:31,082 : DEBUG : ModeController : Loaded mode ball_hold_tracker
2019-05-28 21:22:31,130 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\ee4432fc011abe94968ff81513361e18.mpf_cache
2019-05-28 21:22:31,291 : DEBUG : ModeController : Loaded mode final_hold
2019-05-28 21:22:31,333 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\c35ad2e595070cac0b6f696d6f7f6af6.mpf_cache
2019-05-28 21:22:31,363 : DEBUG : ModeController : Loaded mode ball_save
2019-05-28 21:22:31,364 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\Wilder\zelda\modes\bottle_filler\config\bottle_filler.yaml
2019-05-28 21:22:31,364 : INFO : ConfigProcessor : Loading config from file C:\Users\Wilder\zelda\modes\bottle_filler\config\bottle_filler.yaml.
2019-05-28 21:22:31,364 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\modes\bottle_filler\config\bottle_filler.yaml
2019-05-28 21:22:31,558 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\modes\bottle_filler\config\bottle_filler.yaml
2019-05-28 21:22:31,560 : INFO : ConfigProcessor : Config file cache created: C:\Users\Wilder\AppData\Local\Temp\34c6448537d1c95c89cf73a07c0f99c9.mpf_cache
2019-05-28 21:22:31,571 : DEBUG : ModeController : Loaded mode bottle_filler
2019-05-28 21:22:31,585 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\916c9e2d9177837f45e9cdbb7c1d0b93.mpf_cache
2019-05-28 21:22:31,595 : DEBUG : ModeController : Loaded mode unusual_show_tracker
2019-05-28 21:22:31,624 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\6eb8b6e4728e10ce756703e43167d298.mpf_cache
2019-05-28 21:22:31,658 : DEBUG : ModeController : Loaded mode rupee2x_finder
2019-05-28 21:22:31,720 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\f394a72c4810bb1cc42cac0690a90dcf.mpf_cache
2019-05-28 21:22:31,725 : DEBUG : ModeController : Loaded mode gameoverplayer
2019-05-28 21:22:31,777 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\225554da95d8871f7382aa94a6d6b3eb.mpf_cache
2019-05-28 21:22:31,976 : DEBUG : ModeController : Loaded mode lost_woods_starter
2019-05-28 21:22:32,144 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\b0ee6a771658ae3fb7e70c6d5ff59887.mpf_cache
2019-05-28 21:22:32,563 : DEBUG : ModeController : Loaded mode game
2019-05-28 21:22:32,843 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\27a949ddf2d3e5eeb9247bd991aba200.mpf_cache
2019-05-28 21:22:32,863 : DEBUG : ModeController : Loaded mode darkworld2
2019-05-28 21:22:32,865 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\58a9cd5447353eacedab412f1c10b0ab.mpf_cache
2019-05-28 21:22:32,887 : DEBUG : ModeController : Loaded mode lost_woods
2019-05-28 21:22:32,889 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\8b601767b8d464abeaa513b42e6346a8.mpf_cache
2019-05-28 21:22:32,916 : DEBUG : ModeController : Loaded mode master_sword_buildup
2019-05-28 21:22:32,918 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\58664c35241624b07b13025a5964d2a4.mpf_cache
2019-05-28 21:22:32,938 : DEBUG : ModeController : Loaded mode video_player
2019-05-28 21:22:32,940 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\7b0dcc699efc7732bf9d3e57ee202517.mpf_cache
2019-05-28 21:22:32,958 : DEBUG : ModeController : Loaded mode 2ballescape
2019-05-28 21:22:33,020 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\da675f6b180b79eecb40cb5eb7f75a18.mpf_cache
2019-05-28 21:22:33,059 : DEBUG : ModeController : Loaded mode bomb_finder
2019-05-28 21:22:33,061 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\28e1731e516595966b3afcb08910cb63.mpf_cache
2019-05-28 21:22:33,087 : DEBUG : ModeController : Loaded mode heart_tracker
2019-05-28 21:22:33,089 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\Wilder\zelda\modes\item_tracker\config\item_tracker.yaml
2019-05-28 21:22:33,090 : INFO : ConfigProcessor : Loading config from file C:\Users\Wilder\zelda\modes\item_tracker\config\item_tracker.yaml.
2019-05-28 21:22:33,090 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\modes\item_tracker\config\item_tracker.yaml
2019-05-28 21:22:33,401 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...olumn 13\'',)>) at c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py:96
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...olumn 13\'',)>) at c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py:96>
Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 198, in load
    config = self.process(f)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 224, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 104, in get_single_data
    return self.construct_document(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 114, in construct_document
    for dummy in generator:
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 611, in construct_yaml_map
    value = self.construct_mapping(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 135, in construct_mapping
    format(key, key_node.start_mark))
KeyError: 'Key "repeat" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\item_tracker\\config\\item_tracker.yaml", line 387, column 13'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 99, in _async_handler_done
    future.result()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 117, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 266, in _load_mode
    config = self._load_mode_config(mode_string)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 184, in _load_mode_config
    store_to_cache=self.machine.options['create_config_cache'])
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 132, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 99, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 212, in load
    raise ValueError(msg)
ValueError: Error found in file C:\Users\Wilder\zelda\modes\item_tracker\config\item_tracker.yaml: 'Key "repeat" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\item_tracker\\config\\item_tracker.yaml", line 387, column 13'
2019-05-28 21:22:33,438 : INFO : Machine : Starting the main run loop.
2019-05-28 21:22:33,439 : INFO : Machine : Shutting down...
2019-05-28 21:22:33,439 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2019-05-28 21:22:33,440 : ERROR : FAST : Stop called on serial connection \\.\COM12
2019-05-28 21:22:33,440 : ERROR : FAST : Stop called on serial connection \\.\COM11
2019-05-28 21:22:33,787 : ERROR : root : Error found in file C:\Users\Wilder\zelda\modes\item_tracker\config\item_tracker.yaml: 'Key "repeat" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\item_tracker\\config\\item_tracker.yaml", line 387, column 13'
Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 198, in load
    config = self.process(f)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 224, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 104, in get_single_data
    return self.construct_document(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 114, in construct_document
    for dummy in generator:
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 611, in construct_yaml_map
    value = self.construct_mapping(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 135, in construct_mapping
    format(key, key_node.start_mark))
KeyError: 'Key "repeat" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\item_tracker\\config\\item_tracker.yaml", line 387, column 13'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\commands\game.py", line 220, in __init__
    MachineController(mpf_path, machine_path, vars(self.args)).run()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 716, in run
    self._run_loop()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 776, in _run_loop
    raise self._exception['exception']
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 99, in _async_handler_done
    future.result()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 117, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 266, in _load_mode
    config = self._load_mode_config(mode_string)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 184, in _load_mode_config
    store_to_cache=self.machine.options['create_config_cache'])
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 132, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 99, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 212, in load
    raise ValueError(msg)
ValueError: Error found in file C:\Users\Wilder\zelda\modes\item_tracker\config\item_tracker.yaml: 'Key "repeat" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\item_tracker\\config\\item_tracker.yaml", line 387, column 13'
